apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog
type: Opaque
stringData:
  jwt-secret: "production-jwt-secret-change-this"

  db-auth-url: "postgresql://postgres:Quant1234@admin.cvai40yy8j0h.ap-south-1.rds.amazonaws.com:5432/auth_db?sslmode=verify-full"

  db-posts-url: "postgresql://postgres:Quant1234@admin.cvai40yy8j0h.ap-south-1.rds.amazonaws.com:5432/posts_db?sslmode=verify-full"

  db-comments-url: "postgresql://postgres:Quant1234@admin.cvai40yy8j0h.ap-south-1.rds.amazonaws.com:5432/comments_db?sslmode=verify-full"
