apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog
type: Opaque
stringData:
  jwt-secret: "production-jwt-secret-change-this"

  db-auth-url: "postgresql://postgres:Quant1234@<RDS_ENDPOINT>:5432/blogspace?sslmode=require"

  db-posts-url: "postgresql://postgres:Quant1234@<RDS_ENDPOINT>:5432/blogspace?sslmode=require"

  db-comments-url: "postgresql://postgres:Quant1234@<RDS_ENDPOINT>:5432/blogspace?sslmode=require"
